version: "3"

services:
  frontend:
    image: portainer/portainer
    container_name: portainer_frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - traefik-proxy
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer_insecure.entrypoints=web
      - traefik.http.routers.portainer_insecure.rule=Host(`portainer.domain.com`)
      - traefik.http.routers.portainer_insecure.middlewares=redirect@file

      - traefik.http.routers.portainer.entrypoints=web-secure
      - traefik.http.routers.portainer.rule=Host(`portainer.domain.com`)
      - traefik.http.routers.portainer.tls.certresolver=letsencrypt
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.docker.network=traefik-proxy
    restart: unless-stopped

networks:
  traefik-proxy:
    external: true

volumes:
  portainer_data:
